### ISSUE TITLE
Different pyansys advanced template name when using list and new --help

### ISSUE THREAD

**Issue by phxnsharp** [pyansys/pyansys-templates#22]
I cannot create a pyansys_advanced with this script. I receive the following error:

```bash
(venv) nsharp@ubuntu:~/ver/PyVarTypes/t$ ansys-templates new pyansys_advanced
Usage: ansys-templates new [OPTIONS] COMMAND [ARGS]...
Try 'ansys-templates new --help' for help.

Error: No such command 'pyansys_advanced'.
```

Using `pybasic` or `pyansys` works fine.

**Comment by phxnsharp** [comment]
```bash
(venv) nsharp@ubuntu:~/ver/PyVarTypes/t$ python --version
Python 3.8.0
(venv) nsharp@ubuntu:~/ver/PyVarTypes/t$ pip --version
pip 22.0.4 from /home/nsharp/ver/PyVarTypes/venv/lib/python3.8/site-packages/pip (python 3.8)
(venv) nsharp@ubuntu:~/ver/PyVarTypes/t$ pipx --version
1.0.0
(venv) nsharp@ubuntu:~/ver/PyVarTypes/t$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

(venv) nsharp@ubuntu:~/ver/PyVarTypes/t$ ansys-templates version
ansys-templates 0.1.dev0
```

**Comment by phxnsharp** [comment]
That works, thanks. Note, that I was cut-n-pasting the argument from a call to `ansys-templates list` to be sure that it wasn't me mis-typing anything. So the bug is that the documentation and `ansys-templates list` both are wrong.

**Comment by jorgepiloto** [comment]
I can confirm locally that the `ansys-templates list` command shows `pyansys_advanced` while `ansys-templates new --help` shows `pyansys-advanced`. This is a bug indeed. Thanks for the feedback @phxnsharp, renaming the issue.
